-- Task
-- Query LONG_W where the LAT_N in Station is greater than 38.7780
-- Round your answer to 4 decimal places.

-- SELECT ROUND(LONG_W,4) FROM
-- 	(
-- 		SELECT LAT_N, LONG_W FROM STATION
-- 		WHERE LAT_N > 38.7780
-- 		ORDER BY LAT_N ASC
-- 		LIMIT 1
--     ) as myalias;